default: &default
  adapter: mysql2
  encoding: utf8
  host: <%=ENV['DB_HOST']%>
  port: <%=ENV['DB_PORT']%>
  username: <%=ENV['DB_USER_NAME']%>
  password: <%=ENV['DB_PASSWORD']%>

development:
  <<: *default
  database: <%=ENV['DB_DEV_NAME']%>

test:
  <<: *default
  database: <%=ENV['DB_TEST_NAME']%>

production:
  <<: *default
  database: <%=ENV['DB_PROD_NAME']%>