default: &default
  adapter: mysql2
  encoding: utf8
  host: <%=ENV['DB_HOST']%>
  port: <%=ENV['DB_PORT']%>
  username: <%=ENV['DB_USER_NAME']%>
  password: <%=ENV['DB_PASSWORD']%>

development:
  <<: *default
  database: ticketee2_dev

test:
  <<: *default
  database: ticketee2_test

production:
  <<: *default
  database: ticketee2_prod